INSERT INTO arsenal (project, album, track_number, track_title, file_name, url) VALUES
('HAWK-ARS-00', NULL, 1, '_ 🦅 HAWK EYE THE RAPPER_ The Voice of a Generatio', '_ 🦅 HAWK EYE THE RAPPER_ The Voice of a Generatio', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/_ 🦅 HAWK EYE THE RAPPER_ The Voice of a Generatio.md'),
('HAWK-ARS-00', NULL, 2, '# Hawk’s Nest', '# Hawk’s Nest', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/# Hawk’s Nest.html'),
('HAWK-ARS-00', NULL, 3, '│   ├── 01_will_you_listen', '│   ├── 01_will_you_listen', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 01_will_you_listen.ipynb'),
('HAWK-ARS-00', NULL, 4, '│   ├── 01_will_you_listen', '│   ├── 01_will_you_listen', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 01_will_you_listen.md'),
('HAWK-ARS-00', NULL, 5, '│   ├── 02_psyops', '│   ├── 02_psyops', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 02_psyops.ipynb'),
('HAWK-ARS-00', NULL, 6, '│   ├── 02_psyops', '│   ├── 02_psyops', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 02_psyops.md'),
('HAWK-ARS-00', NULL, 7, '│   ├── 03_incantations', '│   ├── 03_incantations', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 03_incantations.ipynb'),
('HAWK-ARS-00', NULL, 8, '│   ├── 03_incantations', '│   ├── 03_incantations', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 03_incantations.md'),
('HAWK-ARS-00', NULL, 9, '│   ├── 04_mind_kontrol', '│   ├── 04_mind_kontrol', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 04_mind_kontrol.ipynb'),
('HAWK-ARS-00', NULL, 10, '│   ├── 04_mind_kontrol', '│   ├── 04_mind_kontrol', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 04_mind_kontrol.md'),
('HAWK-ARS-00', NULL, 11, '│   ├── 05_return_of_kings', '│   ├── 05_return_of_kings', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 05_return_of_kings.ipynb'),
('HAWK-ARS-00', NULL, 12, '│   ├── 05_return_of_kings', '│   ├── 05_return_of_kings', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 05_return_of_kings.md'),
('HAWK-ARS-00', NULL, 13, '│   ├── 06_politicians', '│   ├── 06_politicians', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 06_politicians.ipynb'),
('HAWK-ARS-00', NULL, 14, '│   ├── 06_politicians', '│   ├── 06_politicians', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 06_politicians.md'),
('HAWK-ARS-00', NULL, 15, '│   ├── 07_the_vow', '│   ├── 07_the_vow', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 07_the_vow.ipynb'),
('HAWK-ARS-00', NULL, 16, '│   ├── 07_the_vow', '│   ├── 07_the_vow', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── 07_the_vow.md'),
('HAWK-ARS-00', NULL, 17, '│   └── Singles_Arsenal', '│   └── Singles_Arsenal', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   └── Singles_Arsenal.md'),
('HAWK-ARS-00', NULL, 18, '│   │   ├── 01_swordfish', '│   │   ├── 01_swordfish', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 01_swordfish.ipynb'),
('HAWK-ARS-00', NULL, 19, '│   │   ├── 01_swordfish', '│   │   ├── 01_swordfish', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 01_swordfish.md'),
('HAWK-ARS-00', NULL, 20, '│   │   ├── 02_full_disclosure_lyrics-compilation', '│   │   ├── 02_full_disclosure_lyrics-compilation', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 02_full_disclosure_lyrics-compilation.html'),
('HAWK-ARS-00', NULL, 21, '│   │   ├── 02_mic_check', '│   │   ├── 02_mic_check', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 02_mic_check.ipynb'),
('HAWK-ARS-00', NULL, 22, '│   │   ├── 02_mic_check', '│   │   ├── 02_mic_check', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 02_mic_check.md'),
('HAWK-ARS-00', NULL, 23, '│   │   ├── 03_shakur', '│   │   ├── 03_shakur', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 03_shakur.ipynb'),
('HAWK-ARS-00', NULL, 24, '│   │   ├── 03_shakur', '│   │   ├── 03_shakur', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 03_shakur.md'),
('HAWK-ARS-00', NULL, 25, '│   │   ├── 04_last_one_left', '│   │   ├── 04_last_one_left', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 04_last_one_left.ipynb'),
('HAWK-ARS-00', NULL, 26, '│   │   ├── 04_last_one_left', '│   │   ├── 04_last_one_left', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 04_last_one_left.md'),
('HAWK-ARS-00', NULL, 27, '│   │   ├── 05_full_disclosure', '│   │   ├── 05_full_disclosure', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 05_full_disclosure.ipynb'),
('HAWK-ARS-00', NULL, 28, '│   │   ├── 05_full_disclosure', '│   │   ├── 05_full_disclosure', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 05_full_disclosure.md'),
('HAWK-ARS-00', NULL, 29, '│   │   ├── 06_lifted', '│   │   ├── 06_lifted', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 06_lifted.ipynb'),
('HAWK-ARS-00', NULL, 30, '│   │   ├── 06_lifted', '│   │   ├── 06_lifted', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 06_lifted.md'),
('HAWK-ARS-00', NULL, 31, '│   │   ├── 07_fuck_society', '│   │   ├── 07_fuck_society', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 07_fuck_society.ipynb'),
('HAWK-ARS-00', NULL, 32, '│   │   ├── 07_fuck_society', '│   │   ├── 07_fuck_society', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 07_fuck_society.md'),
('HAWK-ARS-00', NULL, 33, '│   │   ├── 08_ashes', '│   │   ├── 08_ashes', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 08_ashes.ipynb'),
('HAWK-ARS-00', NULL, 34, '│   │   ├── 08_ashes', '│   │   ├── 08_ashes', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 08_ashes.md'),
('HAWK-ARS-00', NULL, 35, '│   │   ├── 09_haunted', '│   │   ├── 09_haunted', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 09_haunted.ipynb'),
('HAWK-ARS-00', NULL, 36, '│   │   ├── 09_haunted', '│   │   ├── 09_haunted', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 09_haunted.md'),
('HAWK-ARS-00', NULL, 37, '│   │   ├── 10_monumental', '│   │   ├── 10_monumental', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 10_monumental.ipynb'),
('HAWK-ARS-00', NULL, 38, '│   │   ├── 10_monumental', '│   │   ├── 10_monumental', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 10_monumental.md'),
('HAWK-ARS-00', NULL, 39, '│   │   ├── 11_trafficked_web', '│   │   ├── 11_trafficked_web', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 11_trafficked_web.md'),
('HAWK-ARS-00', NULL, 40, '│   │   ├── 11_trafficked', '│   │   ├── 11_trafficked', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 11_trafficked.ipynb'),
('HAWK-ARS-00', NULL, 41, '│   │   ├── 11_trafficked', '│   │   ├── 11_trafficked', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 11_trafficked.md'),
('HAWK-ARS-00', NULL, 42, '│   │   ├── 12_hocus_pocus', '│   │   ├── 12_hocus_pocus', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 12_hocus_pocus.ipynb'),
('HAWK-ARS-00', NULL, 43, '│   │   ├── 12_hocus_pocus', '│   │   ├── 12_hocus_pocus', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 12_hocus_pocus.md'),
('HAWK-ARS-00', NULL, 44, '│   │   ├── 13_syntax', '│   │   ├── 13_syntax', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 13_syntax.ipynb'),
('HAWK-ARS-00', NULL, 45, '│   │   ├── 13_syntax', '│   │   ├── 13_syntax', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 13_syntax.md'),
('HAWK-ARS-00', NULL, 46, '│   │   ├── 14_stay_real', '│   │   ├── 14_stay_real', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 14_stay_real.ipynb'),
('HAWK-ARS-00', NULL, 47, '│   │   ├── 14_stay_real', '│   │   ├── 14_stay_real', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 14_stay_real.md'),
('HAWK-ARS-00', NULL, 48, '│   │   ├── 15_the_story_of_our_former_glory', '│   │   ├── 15_the_story_of_our_former_glory', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 15_the_story_of_our_former_glory.ipynb'),
('HAWK-ARS-00', NULL, 49, '│   │   ├── 15_the_story_of_our_former_glory', '│   │   ├── 15_the_story_of_our_former_glory', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 15_the_story_of_our_former_glory.md'),
('HAWK-ARS-00', NULL, 50, '│   │   ├── EverLightsCriticalSynopsis', '│   │   ├── EverLightsCriticalSynopsis', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── EverLightsCriticalSynopsis.ipynb'),
('HAWK-ARS-00', NULL, 51, '│   │   └── FullDisclosure_Arsenal', '│   │   └── FullDisclosure_Arsenal', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   └── FullDisclosure_Arsenal.md'),
('HAWK-ARS-00', NULL, 52, '│   │   ├── 01_warning_shots', '│   │   ├── 01_warning_shots', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 01_warning_shots.ipynb'),
('HAWK-ARS-00', NULL, 53, '│   │   ├── 01_warning_shots', '│   │   ├── 01_warning_shots', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 01_warning_shots.md'),
('HAWK-ARS-00', NULL, 54, '│   │   ├── 02_behold_a_pale_horse', '│   │   ├── 02_behold_a_pale_horse', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 02_behold_a_pale_horse.ipynb'),
('HAWK-ARS-00', NULL, 55, '│   │   ├── 02_behold_a_pale_horse', '│   │   ├── 02_behold_a_pale_horse', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 02_behold_a_pale_horse.md'),
('HAWK-ARS-00', NULL, 56, '│   │   ├── 03_kamikaze', '│   │   ├── 03_kamikaze', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 03_kamikaze.ipynb'),
('HAWK-ARS-00', NULL, 57, '│   │   ├── 03_kamikaze', '│   │   ├── 03_kamikaze', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 03_kamikaze.md'),
('HAWK-ARS-00', NULL, 58, '│   │   ├── 04_whistleblower', '│   │   ├── 04_whistleblower', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 04_whistleblower.ipynb'),
('HAWK-ARS-00', NULL, 59, '│   │   ├── 04_whistleblower', '│   │   ├── 04_whistleblower', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 04_whistleblower.md'),
('HAWK-ARS-00', NULL, 60, '│   │   ├── 05_superstitions', '│   │   ├── 05_superstitions', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 05_superstitions.ipynb'),
('HAWK-ARS-00', NULL, 61, '│   │   ├── 05_superstitions', '│   │   ├── 05_superstitions', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 05_superstitions.md'),
('HAWK-ARS-00', NULL, 62, '│   │   ├── 06_scripture', '│   │   ├── 06_scripture', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 06_scripture.ipynb'),
('HAWK-ARS-00', NULL, 63, '│   │   ├── 06_scripture', '│   │   ├── 06_scripture', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 06_scripture.md'),
('HAWK-ARS-00', NULL, 64, '│   │   ├── 07_menace_to_society', '│   │   ├── 07_menace_to_society', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 07_menace_to_society.ipynb'),
('HAWK-ARS-00', NULL, 65, '│   │   ├── 07_menace_to_society', '│   │   ├── 07_menace_to_society', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 07_menace_to_society.md'),
('HAWK-ARS-00', NULL, 66, '│   │   ├── 08_semi-automatic', '│   │   ├── 08_semi-automatic', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 08_semi-automatic.ipynb'),
('HAWK-ARS-00', NULL, 67, '│   │   ├── 08_semi-automatic', '│   │   ├── 08_semi-automatic', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 08_semi-automatic.md'),
('HAWK-ARS-00', NULL, 68, '│   │   ├── 09_reverse_this_curse', '│   │   ├── 09_reverse_this_curse', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 09_reverse_this_curse.ipynb'),
('HAWK-ARS-00', NULL, 69, '│   │   ├── 09_reverse_this_curse', '│   │   ├── 09_reverse_this_curse', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 09_reverse_this_curse.md'),
('HAWK-ARS-00', NULL, 70, '│   │   ├── 10_kt', '│   │   ├── 10_kt', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 10_kt.ipynb'),
('HAWK-ARS-00', NULL, 71, '│   │   ├── 10_kt', '│   │   ├── 10_kt', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 10_kt.md'),
('HAWK-ARS-00', NULL, 72, '│   │   ├── 11_the_story_celebrated_throughout_time', '│   │   ├── 11_the_story_celebrated_throughout_time', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 11_the_story_celebrated_throughout_time.ipynb'),
('HAWK-ARS-00', NULL, 73, '│   │   ├── 11_the_story_celebrated_throughout_time', '│   │   ├── 11_the_story_celebrated_throughout_time', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 11_the_story_celebrated_throughout_time.md'),
('HAWK-ARS-00', NULL, 74, '│   │   ├── BAPH-LMA_baphlyrics-compilation', '│   │   ├── BAPH-LMA_baphlyrics-compilation', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── BAPH-LMA_baphlyrics-compilation.html'),
('HAWK-ARS-00', NULL, 75, '│   │   ├── BeholdAPaleHorse_Arsenal', '│   │   ├── BeholdAPaleHorse_Arsenal', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── BeholdAPaleHorse_Arsenal.md'),
('HAWK-ARS-00', NULL, 76, '│   │   ├── EverLightsInitialThoughts', '│   │   ├── EverLightsInitialThoughts', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── EverLightsInitialThoughts.ipynb'),
('HAWK-ARS-00', NULL, 77, '│   │   ├── EverLightsInitialThoughts', '│   │   ├── EverLightsInitialThoughts', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── EverLightsInitialThoughts.md'),
('HAWK-ARS-00', NULL, 78, '│   │   ├── EverLightsRite', '│   │   ├── EverLightsRite', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── EverLightsRite.ipynb'),
('HAWK-ARS-00', NULL, 79, '│   │   └── EverLightsRite', '│   │   └── EverLightsRite', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   └── EverLightsRite.md'),
('HAWK-ARS-00', NULL, 80, '│   │   ├── 01_soft_disclosure', '│   │   ├── 01_soft_disclosure', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 01_soft_disclosure.ipynb'),
('HAWK-ARS-00', NULL, 81, '│   │   ├── 01_soft_disclosure', '│   │   ├── 01_soft_disclosure', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 01_soft_disclosure.md'),
('HAWK-ARS-00', NULL, 82, '│   │   ├── 02_abreactions', '│   │   ├── 02_abreactions', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 02_abreactions.ipynb'),
('HAWK-ARS-00', NULL, 83, '│   │   ├── 02_abreactions', '│   │   ├── 02_abreactions', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 02_abreactions.md'),
('HAWK-ARS-00', NULL, 84, '│   │   ├── 03_eyes_wide_open', '│   │   ├── 03_eyes_wide_open', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 03_eyes_wide_open.ipynb'),
('HAWK-ARS-00', NULL, 85, '│   │   ├── 03_eyes_wide_open', '│   │   ├── 03_eyes_wide_open', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 03_eyes_wide_open.md'),
('HAWK-ARS-00', NULL, 86, '│   │   ├── 04_delta_squad', '│   │   ├── 04_delta_squad', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 04_delta_squad.ipynb'),
('HAWK-ARS-00', NULL, 87, '│   │   ├── 04_delta_squad', '│   │   ├── 04_delta_squad', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 04_delta_squad.md'),
('HAWK-ARS-00', NULL, 88, '│   │   ├── 05_implants', '│   │   ├── 05_implants', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 05_implants.ipynb'),
('HAWK-ARS-00', NULL, 89, '│   │   ├── 05_implants', '│   │   ├── 05_implants', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 05_implants.md'),
('HAWK-ARS-00', NULL, 90, '│   │   ├── 06_illuminati', '│   │   ├── 06_illuminati', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 06_illuminati.ipynb'),
('HAWK-ARS-00', NULL, 91, '│   │   ├── 06_illuminati', '│   │   ├── 06_illuminati', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 06_illuminati.md'),
('HAWK-ARS-00', NULL, 92, '│   │   ├── 07_fema', '│   │   ├── 07_fema', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 07_fema.ipynb'),
('HAWK-ARS-00', NULL, 93, '│   │   ├── 07_fema', '│   │   ├── 07_fema', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 07_fema.md'),
('HAWK-ARS-00', NULL, 94, '│   │   ├── 08_the_antidote', '│   │   ├── 08_the_antidote', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 08_the_antidote.ipynb'),
('HAWK-ARS-00', NULL, 95, '│   │   ├── 08_the_antidote', '│   │   ├── 08_the_antidote', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 08_the_antidote.md'),
('HAWK-ARS-00', NULL, 96, '│   │   ├── 09_avalanche', '│   │   ├── 09_avalanche', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 09_avalanche.ipynb'),
('HAWK-ARS-00', NULL, 97, '│   │   ├── 09_avalanche', '│   │   ├── 09_avalanche', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 09_avalanche.md'),
('HAWK-ARS-00', NULL, 98, '│   │   ├── 10_artificial_intelligence', '│   │   ├── 10_artificial_intelligence', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 10_artificial_intelligence.ipynb'),
('HAWK-ARS-00', NULL, 99, '│   │   ├── 10_artificial_intelligence', '│   │   ├── 10_artificial_intelligence', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 10_artificial_intelligence.md'),
('HAWK-ARS-00', NULL, 100, '│   │   ├── 11_legion', '│   │   ├── 11_legion', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 11_legion.ipynb'),
('HAWK-ARS-00', NULL, 101, '│   │   ├── 11_legion', '│   │   ├── 11_legion', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 11_legion.md'),
('HAWK-ARS-00', NULL, 102, '│   │   ├── 12_when_my_elites_surround', '│   │   ├── 12_when_my_elites_surround', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 12_when_my_elites_surround.ipynb'),
('HAWK-ARS-00', NULL, 103, '│   │   ├── 12_when_my_elites_surround', '│   │   ├── 12_when_my_elites_surround', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 12_when_my_elites_surround.md'),
('HAWK-ARS-00', NULL, 104, '│   │   ├── 13_reincarnated_2_resist', '│   │   ├── 13_reincarnated_2_resist', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 13_reincarnated_2_resist.ipynb'),
('HAWK-ARS-00', NULL, 105, '│   │   ├── 13_reincarnated_2_resist', '│   │   ├── 13_reincarnated_2_resist', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 13_reincarnated_2_resist.md'),
('HAWK-ARS-00', NULL, 106, '│   │   ├── EverLightsRite_TheMixtapeSessions', '│   │   ├── EverLightsRite_TheMixtapeSessions', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── EverLightsRite_TheMixtapeSessions.ipynb'),
('HAWK-ARS-00', NULL, 107, '│   │   ├── EverLightsRite_TheMixtapeSessions', '│   │   ├── EverLightsRite_TheMixtapeSessions', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── EverLightsRite_TheMixtapeSessions.md'),
('HAWK-ARS-00', NULL, 108, '│   │   ├── Milabs_Arsenal', '│   │   ├── Milabs_Arsenal', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── Milabs_Arsenal.md'),
('HAWK-ARS-00', NULL, 109, '│   │   └── Milabs_Lyric_Compilation', '│   │   └── Milabs_Lyric_Compilation', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   └── Milabs_Lyric_Compilation.html'),
('HAWK-ARS-00', NULL, 110, '│   ├── EverLightsRite_TheMixtapeSessions', '│   ├── EverLightsRite_TheMixtapeSessions', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── EverLightsRite_TheMixtapeSessions.ipynb'),
('HAWK-ARS-00', NULL, 111, '│   ├── FullDisclosure_Critical', '│   ├── FullDisclosure_Critical', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── FullDisclosure_Critical.md'),
('HAWK-ARS-00', NULL, 112, '│   ├── Hawk Eye The Rapper – Behold a Pale Horse_ Inspire', '│   ├── Hawk Eye The Rapper – Behold a Pale Horse_ Inspire', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Hawk Eye The Rapper – Behold a Pale Horse_ Inspire.md'),
('HAWK-ARS-00', NULL, 113, '│   ├── Hawk Eye The Rapper – Full Disclosure_ A Tribute t', '│   ├── Hawk Eye The Rapper – Full Disclosure_ A Tribute t', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Hawk Eye The Rapper – Full Disclosure_ A Tribute t.md'),
('HAWK-ARS-00', NULL, 114, '│   ├── Hawk Eye The Rapper – Milabs_ Honoring Dr. Karla T', '│   ├── Hawk Eye The Rapper – Milabs_ Honoring Dr. Karla T', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Hawk Eye The Rapper – Milabs_ Honoring Dr. Karla T.md'),
('HAWK-ARS-00', NULL, 115, '│   ├── Mixtape_Sessions_Archive_Full_Vault', '│   ├── Mixtape_Sessions_Archive_Full_Vault', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Mixtape_Sessions_Archive_Full_Vault.html'),
('HAWK-ARS-00', NULL, 116, '│   ├── Mixtape_Sessions_Archive', '│   ├── Mixtape_Sessions_Archive', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Mixtape_Sessions_Archive.html'),
('HAWK-ARS-00', NULL, 117, '│   ├── Mixtape_Sessions_Archive', '│   ├── Mixtape_Sessions_Archive', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Mixtape_Sessions_Archive.md'),
('HAWK-ARS-00', NULL, 118, '│   └── MixtapeSessions_Arsenal', '│   └── MixtapeSessions_Arsenal', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   └── MixtapeSessions_Arsenal.md'),
('HAWK-ARS-00', NULL, 119, '│   │   ├── 01_malicious', '│   │   ├── 01_malicious', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 01_malicious.ipynb'),
('HAWK-ARS-00', NULL, 120, '│   │   ├── 01-malicious', '│   │   ├── 01-malicious', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 01-malicious.md'),
('HAWK-ARS-00', NULL, 121, '│   │   ├── 02_gang_shit', '│   │   ├── 02_gang_shit', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 02_gang_shit.ipynb'),
('HAWK-ARS-00', NULL, 122, '│   │   ├── 02-gang_shit', '│   │   ├── 02-gang_shit', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 02-gang_shit.md'),
('HAWK-ARS-00', NULL, 123, '│   │   ├── 03_the_motherfucking_problem', '│   │   ├── 03_the_motherfucking_problem', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 03_the_motherfucking_problem.ipynb'),
('HAWK-ARS-00', NULL, 124, '│   │   ├── 03-the_motherfucking_problem', '│   │   ├── 03-the_motherfucking_problem', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 03-the_motherfucking_problem.md'),
('HAWK-ARS-00', NULL, 125, '│   │   ├── 04_im_him', '│   │   ├── 04_im_him', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 04_im_him.ipynb'),
('HAWK-ARS-00', NULL, 126, '│   │   ├── 04-im_him', '│   │   ├── 04-im_him', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 04-im_him.md'),
('HAWK-ARS-00', NULL, 127, '│   │   ├── Malicious_Arsenal', '│   │   ├── Malicious_Arsenal', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── Malicious_Arsenal.md'),
('HAWK-ARS-00', NULL, 128, '│   │   └── Malicious_Lyric_Compilation', '│   │   └── Malicious_Lyric_Compilation', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   └── Malicious_Lyric_Compilation.html'),
('HAWK-ARS-00', NULL, 129, '│   │   ├── 001psychwar', '│   │   ├── 001psychwar', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 001psychwar.md'),
('HAWK-ARS-00', NULL, 130, '│   │   ├── 01_psychological_warfare', '│   │   ├── 01_psychological_warfare', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 01_psychological_warfare.ipynb'),
('HAWK-ARS-00', NULL, 131, '│   │   ├── 01_psychological_warfare', '│   │   ├── 01_psychological_warfare', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 01_psychological_warfare.md'),
('HAWK-ARS-00', NULL, 132, '│   │   ├── 02_down_the_rabbit_hole', '│   │   ├── 02_down_the_rabbit_hole', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 02_down_the_rabbit_hole.ipynb'),
('HAWK-ARS-00', NULL, 133, '│   │   ├── 02_down_the_rabbit_hole', '│   │   ├── 02_down_the_rabbit_hole', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 02_down_the_rabbit_hole.md'),
('HAWK-ARS-00', NULL, 134, '│   │   ├── 03_domestic_terrorist', '│   │   ├── 03_domestic_terrorist', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 03_domestic_terrorist.ipynb'),
('HAWK-ARS-00', NULL, 135, '│   │   ├── 03_domestic_terrorist', '│   │   ├── 03_domestic_terrorist', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 03_domestic_terrorist.md'),
('HAWK-ARS-00', NULL, 136, '│   │   ├── 04_relentless', '│   │   ├── 04_relentless', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 04_relentless.ipynb'),
('HAWK-ARS-00', NULL, 137, '│   │   ├── 04_relentless', '│   │   ├── 04_relentless', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 04_relentless.md'),
('HAWK-ARS-00', NULL, 138, '│   │   ├── 05_never_heard_of_me', '│   │   ├── 05_never_heard_of_me', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 05_never_heard_of_me.ipynb'),
('HAWK-ARS-00', NULL, 139, '│   │   ├── 05_never_heard_of_me', '│   │   ├── 05_never_heard_of_me', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 05_never_heard_of_me.md'),
('HAWK-ARS-00', NULL, 140, '│   │   ├── 06_spiteful_poetry', '│   │   ├── 06_spiteful_poetry', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 06_spiteful_poetry.ipynb'),
('HAWK-ARS-00', NULL, 141, '│   │   ├── 06_spiteful_poetry', '│   │   ├── 06_spiteful_poetry', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 06_spiteful_poetry.md'),
('HAWK-ARS-00', NULL, 142, '│   │   ├── 07_devils_in_the_details', '│   │   ├── 07_devils_in_the_details', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 07_devils_in_the_details.md'),
('HAWK-ARS-00', NULL, 143, '│   │   ├── 07_the_devils_in_the_details', '│   │   ├── 07_the_devils_in_the_details', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 07_the_devils_in_the_details.ipynb'),
('HAWK-ARS-00', NULL, 144, '│   │   ├── 08_the_game', '│   │   ├── 08_the_game', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 08_the_game.ipynb'),
('HAWK-ARS-00', NULL, 145, '│   │   ├── 08_the_game', '│   │   ├── 08_the_game', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 08_the_game.md'),
('HAWK-ARS-00', NULL, 146, '│   │   ├── 09_the_shadow_is_rising', '│   │   ├── 09_the_shadow_is_rising', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 09_the_shadow_is_rising.ipynb'),
('HAWK-ARS-00', NULL, 147, '│   │   ├── 09_the_shadow_is_rising', '│   │   ├── 09_the_shadow_is_rising', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 09_the_shadow_is_rising.md'),
('HAWK-ARS-00', NULL, 148, '│   │   ├── 10_when_shit_gets_real', '│   │   ├── 10_when_shit_gets_real', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 10_when_shit_gets_real.ipynb'),
('HAWK-ARS-00', NULL, 149, '│   │   ├── 10_when_shit_gets_real', '│   │   ├── 10_when_shit_gets_real', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 10_when_shit_gets_real.md'),
('HAWK-ARS-00', NULL, 150, '│   │   ├── 11_synthesis', '│   │   ├── 11_synthesis', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 11_synthesis.ipynb'),
('HAWK-ARS-00', NULL, 151, '│   │   ├── 11_synthesis', '│   │   ├── 11_synthesis', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 11_synthesis.md'),
('HAWK-ARS-00', NULL, 152, '│   │   ├── 12_invokation', '│   │   ├── 12_invokation', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 12_invokation.ipynb'),
('HAWK-ARS-00', NULL, 153, '│   │   ├── 12_invokation', '│   │   ├── 12_invokation', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 12_invokation.md'),
('HAWK-ARS-00', NULL, 154, '│   │   ├── 13_krystal_klear', '│   │   ├── 13_krystal_klear', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 13_krystal_klear.ipynb'),
('HAWK-ARS-00', NULL, 155, '│   │   ├── 13_krystal_klear', '│   │   ├── 13_krystal_klear', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── 13_krystal_klear.md'),
('HAWK-ARS-00', NULL, 156, '│   │   ├── Shadow_Banned_Arsenal', '│   │   ├── Shadow_Banned_Arsenal', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   ├── Shadow_Banned_Arsenal.md'),
('HAWK-ARS-00', NULL, 157, '│   │   └── Shadow_Banned_Lyric_Compilation', '│   │   └── Shadow_Banned_Lyric_Compilation', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   └── Shadow_Banned_Lyric_Compilation.html'),
('HAWK-ARS-00', NULL, 158, '│   └── Phase2_Arsenal', '│   └── Phase2_Arsenal', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   └── Phase2_Arsenal.md'),
('HAWK-ARS-00', NULL, 159, '│   ├── Sun_Tzu', '│   ├── Sun_Tzu', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Sun_Tzu.ipynb'),
('HAWK-ARS-00', NULL, 160, '│   ├── SunBook', '│   ├── SunBook', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── SunBook.ipynb'),
('HAWK-ARS-00', NULL, 161, '│   └── SunTzu_Reckoning_Arsenal', '│   └── SunTzu_Reckoning_Arsenal', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   └── SunTzu_Reckoning_Arsenal.md'),
('HAWK-ARS-00', NULL, 162, 'ARS-00', 'ARS-00', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/ARS-00.csv'),
('HAWK-ARS-00', NULL, 163, 'arsenal_catalog', 'arsenal_catalog', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/arsenal_catalog.csv'),
('HAWK-ARS-00', NULL, 164, '│   ├── Behold_A_Pale_Horse', '│   ├── Behold_A_Pale_Horse', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Behold_A_Pale_Horse.md'),
('HAWK-ARS-00', NULL, 165, '│   ├── Full_Disclosure', '│   ├── Full_Disclosure', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Full_Disclosure.md'),
('HAWK-ARS-00', NULL, 166, '│   ├── Malicious_EP', '│   ├── Malicious_EP', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Malicious_EP.md'),
('HAWK-ARS-00', NULL, 167, '│   ├── MILABS', '│   ├── MILABS', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── MILABS.md'),
('HAWK-ARS-00', NULL, 168, '│   ├── Shadow_Banned', '│   ├── Shadow_Banned', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Shadow_Banned.md'),
('HAWK-ARS-00', NULL, 169, '│   └── Singles_Arc', '│   └── Singles_Arc', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   └── Singles_Arc.md'),
('HAWK-ARS-00', NULL, 170, '│   ├── Behold_A_Pale_Horse', '│   ├── Behold_A_Pale_Horse', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Behold_A_Pale_Horse.md'),
('HAWK-ARS-00', NULL, 171, '│   ├── Full_Disclosure', '│   ├── Full_Disclosure', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Full_Disclosure.md'),
('HAWK-ARS-00', NULL, 172, '│   ├── Malicious_EP', '│   ├── Malicious_EP', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Malicious_EP.md'),
('HAWK-ARS-00', NULL, 173, '│   ├── MILABS', '│   ├── MILABS', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── MILABS.md'),
('HAWK-ARS-00', NULL, 174, '│   ├── Phase_II_Hypothesis', '│   ├── Phase_II_Hypothesis', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Phase_II_Hypothesis.md'),
('HAWK-ARS-00', NULL, 175, '│   ├── Singles', '│   ├── Singles', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Singles.md'),
('HAWK-ARS-00', NULL, 176, '│   └── The_Mixtape_Sessions', '│   └── The_Mixtape_Sessions', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   └── The_Mixtape_Sessions.md'),
('HAWK-ARS-00', NULL, 177, '│   ├── BAPH', '│   ├── BAPH', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── BAPH.md'),
('HAWK-ARS-00', NULL, 178, '│   ├── Full_Disclosure', '│   ├── Full_Disclosure', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Full_Disclosure.md'),
('HAWK-ARS-00', NULL, 179, '│   ├── Malicious', '│   ├── Malicious', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Malicious.md'),
('HAWK-ARS-00', NULL, 180, '│   ├── MILABS', '│   ├── MILABS', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── MILABS.md'),
('HAWK-ARS-00', NULL, 181, '│   ├── Phase_II', '│   ├── Phase_II', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── Phase_II.md'),
('HAWK-ARS-00', NULL, 182, '│   ├── README', '│   ├── README', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   ├── README.md'),
('HAWK-ARS-00', NULL, 183, '│   └── Singles', '│   └── Singles', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   └── Singles.md'),
('HAWK-ARS-00', NULL, 184, 'EverLightsRite_TheMixtapeSessions', 'EverLightsRite_TheMixtapeSessions', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/EverLightsRite_TheMixtapeSessions.md'),
('HAWK-ARS-00', NULL, 185, '│   │   └── README', '│   │   └── README', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   └── README.md'),
('HAWK-ARS-00', NULL, 186, '│   │   └── EverLights_Rite', '│   │   └── EverLights_Rite', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   └── EverLights_Rite.md'),
('HAWK-ARS-00', NULL, 187, '│   │   └── EverLights_Rite', '│   │   └── EverLights_Rite', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   └── EverLights_Rite.md'),
('HAWK-ARS-00', NULL, 188, '│   │   └── EverLights_Rite', '│   │   └── EverLights_Rite', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   └── EverLights_Rite.md'),
('HAWK-ARS-00', NULL, 189, '│   │   └── EverLights_Rite', '│   │   └── EverLights_Rite', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   └── EverLights_Rite.md'),
('HAWK-ARS-00', NULL, 190, '│   │   └── EverLights_Rite', '│   │   └── EverLights_Rite', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│   │   └── EverLights_Rite.md'),
('HAWK-ARS-00', NULL, 191, '│       └── PHASE_2_Foreshadowing', '│       └── PHASE_2_Foreshadowing', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/│       └── PHASE_2_Foreshadowing.md'),
('HAWK-ARS-00', NULL, 192, 'Main_Arsenal_Index', 'Main_Arsenal_Index', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/Main_Arsenal_Index.md'),
('HAWK-ARS-00', NULL, 193, 'Master_Index', 'Master_Index', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/Master_Index.ipynb'),
('HAWK-ARS-00', NULL, 194, 'MEDIA', 'MEDIA', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/MEDIA.csv'),
('HAWK-ARS-00', NULL, 195, 'README', 'README', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/README.md'),
('HAWK-ARS-00', NULL, 196, 'The_Archive', 'The_Archive', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/The_Archive.ipynb'),
('HAWK-ARS-00', NULL, 197, 'Unmasking Reality_ Hawk Eye The Rapper_s _Mixtape ', 'Unmasking Reality_ Hawk Eye The Rapper_s _Mixtape ', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/Unmasking Reality_ Hawk Eye The Rapper_s _Mixtape .md'),
('HAWK-ARS-00', NULL, 198, 'Updated_Unified_Reincarnated_Store_Catalog', 'Updated_Unified_Reincarnated_Store_Catalog', 'https://s3.omniversalmedia.app/src/data/HAWK-ARS-00/Updated_Unified_Reincarnated_Store_Catalog.csv');